//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAllowanceImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllowanceConfiguration()
        {
            this.ImportedTransactionAllowances = new HashSet<ImportedTransactionAllowance>();
        }
    
        public int AllowanceConfigId { get; set; }
        public string AllowanceName { get; set; }
        public string ObjectReference { get; set; }
        public string PayrollCode { get; set; }
        public decimal RateFactor { get; set; }
        public bool IsRateMultiplier { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportedTransactionAllowance> ImportedTransactionAllowances { get; set; }
    }
}
