//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAllowanceImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportedTransactionsView
    {
        public int ExportedTransactionId { get; set; }
        public string ExportedPath { get; set; }
        public System.DateTime DateExported { get; set; }
        public int EmployeeCount { get; set; }
        public Nullable<bool> IsExported { get; set; }
        public string FileName { get; set; }
        public int ImportedTransactionId { get; set; }
        public int AllowanceConfigId { get; set; }
        public decimal Amount { get; set; }
        public string AllowanceName { get; set; }
        public string PayrollCode { get; set; }
        public decimal RateFactor { get; set; }
        public decimal Rate { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string EmployeeRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeFullName { get; set; }
        public int EmployeeId { get; set; }
        public string Notes { get; set; }
    }
}
