//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAllowanceImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedTransactionAllowance
    {
        public int ImportedTransactionAllowanceId { get; set; }
        public int ImportedTransactionId { get; set; }
        public int AllowanceConfigId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual AllowanceConfiguration AllowanceConfiguration { get; set; }
        public virtual ImportedTransaction ImportedTransaction { get; set; }
    }
}
