//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAllowanceImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedTransactionHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportedTransactionHeader()
        {
            this.ImportedTransactions = new HashSet<ImportedTransaction>();
        }
    
        public int ImportedTransactionHeaderId { get; set; }
        public string ImportedFilePath { get; set; }
        public System.DateTime DateImported { get; set; }
        public int RecordCount { get; set; }
        public bool IsExported { get; set; }
        public string NewFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportedTransaction> ImportedTransactions { get; set; }
    }
}
